name=C166 Haldex
description=Infineon C166/XC166 language module tuned for Haldex Gen 5 firmware analysis
author=TheFlashBold, based on the C166 language module by Keyhan Asadi
createdOn=2026-06-15
version=12.1.2-haldex3
